Connect watcher to StreamRegistry for subscriptions
streamr-dev/streamr-ethereum-watcher pull request #230
Opened 2022-02-15 09:15 UTC by jtakalai

This maybe could be kept in a separate branch ("brubeck" or something) because it's supposed to run on alongside the current `master` version

2022-02-16 09:19 UTC, samt1803 approved these changes
LGTM!

2022-02-21 11:19 UTC, kare requested changes
Looks like a great start, but some refactoring is required.

- [ ] See question on line 137. Why return types have changed for `watcher.on()`?
- [ ] Why no tests or updates to test files?
- [ ] README needs an update

2022-02-21 11:19 UTC, kare commented on src/CoreAPIClient.ts
> +    private async _get(apiUrl: string): Promise<any> {
Methods for POST and GET should return the same type to make the API uniform and easy to understand.

2022-02-21 11:19 UTC, kare commented on src/main.ts
> +type Permission = {
Why these are type aliases? Should't they be interfaces or classes to allow extensibility?

2022-02-21 11:19 UTC, kare commented on src/main.ts
> +    let provider: ethers.providers.Provider
👍

2022-02-21 11:19 UTC, kare commented on src/main.ts
> +        log.info("Watcher > subscribed event at block %s index %s: until %s", blockNumber, blockIndex, endsAt)
These log messages are written from `main.ts` not `watchers.ts`. Looks like the prefix `Watcher > ...` is a bit misleading?

2022-02-24 13:12 UTC, merged

2022-02-28 08:57 UTC, jtakalai commented on src/main.ts
> -        return Promise.resolve()
async function returns a Promise as-is, no need to explicitly create it. When execution runs off the end of the async function, the promise is resolved (with void type). Use on `any` is bad there, it should be just `void`.